### ISSUE TITLE
Accomodate color specs with slashes

### ISSUE THREAD

**Issue by hanche** [hanche/dokuwiki_color_plugin#10]
When merging #7, I had not looked carefully at the new colour specifications. In particular, the [specification for hwb() colours](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb) uses a forward slash in its syntax, if an alpha value is included.

Some possible solutions:

- Escape convention: A double forward slash to signify a single slash in a colour spec
- Alternate syntax v1: Something like <color `:⟨fg-spec⟩:⟨bg-spec⟩>` which would allow to use forward slashes in the colour specs (but of course disallowing the colon. The colon should be fairly safe to use here, since css uses the colon for different purposes, so it's unlikely to creep into any future colour specification.
- Alternate syntax v2: Like the above, but dropping the initial colon: <color `⟨fg-spec⟩:⟨bg-spec⟩>`. In order to make this unambiguous, a separating colon **must** be part of the syntax, in order to separate it from the first version.

I am more and more tending towards the latter option. It seems more natural, ans should be very easy to implement. @fiwswe: What do you think?

**Comment by hanche** [comment]
I implemented Alternate syntax v2 in the [slashfix](/hanche/dokuwiki_color_plugin/tree/slashfix) branch. I have tested it, somewhat superficially, and it seems to work.

**Comment by fiwswe** [comment]
Interesting! I never noticed that even the `rgba()` syntax allows for `/` to separate the alpha value. Kind of strange if you ask me, but I didn't make the standard.

I'm generally fine with your suggested fix of allowing `:` as an alternate separator in https://github.com/hanche/dokuwiki_color_plugin/tree/slashfix. It doesn't break any existing pages and it allows color specs containing `/`. Though if there is ever a color spec that can contain `/` **and** `:` then you'll need to revisit :-)

But the logic of your fix seems incorrect (unless I am misreading something here):
```
              if (false === strpbrk($str,':')){
                 $m = explode('/', $str);
              } else {
                 $m = explode(':', $str);
              }
```
If there is no `:` and a single color spec that contains a `/` is used, then the result would not be what was intended. E.g.: `<color rgba(1, 2, 3 / .5)>Text</color>` would result in `<span style="color:rgba(1, 2, 3;background-color:.5);">Text</span>` instead of the intended `<span style="color:rgba(1, 2, 3 / .5);">Text</span>`.

I'm not sure about a solution as yet but I suspect a more complicated regex is needed.

**Comment by hanche** [comment]
@fiwswe: Yeah, I was actually aware of the problem you mention. I did mention it in the third bullet point of my message above. The solution is to require a colon in that case, for example like this:

`<color hwb(120 50% 50% / 50%):>some text </color>`

Note the trailing colon. That introduces an empty string for the background color, but that will of course be ignored, so it has no effect.

This solution is of course far from ideal, but I don't want to go down the rabbit hole of more sophisticated parsing. And then, the requirement for backward compatibility leaves few good options. I think it will be possible to live with this, if it is properly documented.

**Comment by fiwswe** [comment]
> I did mention it in the third bullet point of my message above. 

Sorry, you are correct. I missed that.

As exotic as these cases are (to me at least) I agree that a mandatory `:` for disambiguation and documentation would be an acceptable solution.

**Comment by hanche** [comment]
Good, so be it, then.
