### ISSUE TITLE
Headers Breaks or Ignored

### ISSUE THREAD

**Issue by mwsasser** [hanche/dokuwiki_color_plugin#2]
When used with Headers, there are two problems.

The below will break the header.  It appears with color but loses it's title formatting entirely.
```
<color blue>
==== Title ====
</color>
```

The below will appear as text within the header.  No color will appear.
```
==== <color blue> Title </color> ====
```

I don't see anything about these limitations in the Usage Notes.  Any chance of an update that will allow for those case options?

**Comment by hanche** [comment]
First, since `<color>` creates a `<span>` element in the HTML, and titles are block level elements, you cannot nest the latter inside the former.

Second, I think it's documented elsewhere that no markup applies inside a title (but I'll look to be sure).

This could have been better documented, though. I'll look into it.

**Comment by hanche** [comment]
Definitely [no formatting inside a header](https://www.dokuwiki.org/faq:headerlinks). So what remains is just documenting this better.

**Comment by hanche** [comment]
I added some comments on the [plugin's information page](https://www.dokuwiki.org/plugin:color#usage).
