### ISSUE TITLE
hsl(0deg,100%,100%) does not work

### ISSUE THREAD

**Issue by fiwswe** [hanche/dokuwiki_color_plugin#6]
`hsl()`and `hsla()` color specifications with a unit designation for the hue parameter (as specified in [HSL color model](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#hsl_color_model)) do not work. Currently the allowed units are `deg`, `rad`, `grad` and `turn`. No unit defaults to mean `deg` which does work.

The reason seems to be that the method `_isValid()` does not recognize the units as valid syntax.

Would it make sense to disable the validation entirely and let the browser interpret the values as given? That would have the benefit of accepting any color specification in whatever form future versions of HTML/CSS may allow. Maybe just make sure that no `;` is present, as that might allow unrelated extra CSS to be placed into the color specification, e.g. `<color #f00;font-size:20em>Test</color>` would lead to `<span style="color:#f00;font-size:20em;">Test</span>` being generated. We don't want that as it would have security implications!

[color syntax plugin](https://www.dokuwiki.org/plugin:color) version 2022-09-15, DokuWiki 2022-07-31a "Igor" and 2022-07-29a "Hogfather"

**Comment by hanche** [comment]
Thanks for posting this issue and the related PR.

Yes, I think it is a good idea not to try to second guess future additions to the colour spec, and hence to disable validation altogether. I had wanted to do so back when I submitted my own PR to enable hsl and rgb, but since it wasn't my project, I opted for a less radical solution.

I have a few comments regarding implementation, but I'll add those to your PR instead.
